### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by pyq881120** [ethbets/ebets#7]
ERROR in ./src/index.js
Module not found: Error: Can't resolve 'react-web3' in '/var/ebets/ebets/front/src'
 @ ./src/index.js 37:16-37
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

**Comment by r0qs** [comment]
Hello @pyq881120, thank you for the report. I fixed the problem, could you try to pull the master again, delete your node_modules and reinstall?

**Comment by r0qs** [comment]
Duplicated: https://github.com/ethbets/ebets/issues/8
