### ISSUE TITLE
webpack packaging still failed(npm start)

### ISSUE THREAD

**Issue by pyq881120** [ethbets/ebets#8]
ERROR in ./src/index.js
Module not found: Error: Can't resolve 'react-web3' in '/var/ebets/ebets/front/src'
 @ ./src/index.js 37:16-37
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./src/index.js
webpack: Failed to compile.

**Comment by r0qs** [comment]
Hello @pyq881120 you tried to pull the repository, remove your old node_modules and run npm install again?

I cloned a fresh copy of repository in my machine and all works fine. And please, use the same open issue for the discussion about the same problem, I will close the first ok?

**Comment by pyq881120** [comment]
hello @r0qs  
In my CentOS7 , I found after excute npm install, react-web module installation problem, it seems that the path is wrong, I manually handle a bit, then  npm start execution success(webpack compiled successfully), when I access Http://127.0.0.1:8080/, can not see anything, the entire page is black, but the page title shows Ebets, I think the process is running out, but I do not know why the interface did not show up

**Comment by r0qs** [comment]
Hello @pyq881120,

Do you have [MetaMask](https://metamask.io/) installed in your browser? Currently it is necessary to work.
